spring.application.name=Subtrack_Backend
server.port=8080

# DATABASE CONFIGURATION (aaPanel Production)
spring.datasource.url=jdbc:postgresql://localhost:5432/subtrack
spring.datasource.username=subtrack
spring.datasource.password=A2yXX45wtY8DLfZ4
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# JWT CONFIGURATION
jwt.secret=SubTrackSecretKeyForJWTAuthenticationMustBeLongEnough2026!
jwt.expiration=86400000

# EMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=israadvisuals@gmail.com
spring.mail.password=vuemzdirmcnnqpls
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
