spring.application.name=Subtrack_Backend
server.port=8080
# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/subtrack_db
spring.datasource.username=postgres
spring.datasource.password=Kadmalla$1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIGURATION

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT CONFIGURATION
# Secret key must be 32+ characters for HS256
jwt.secret=SubTrackSecretKeyForJWTAuthenticationMustBeLongEnough2026!
jwt.expiration=86400000
# 86400000 milliseconds = 24 hours (login lasts 24h)